version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: histogrammar
    versions:
    - 1.0.20
    - 1.0.21
    - 1.0.23