# See: https://docs.readthedocs.io/en/latest/yaml-config.html
# .readthedocs.yml

build:
  image: latest

python:
  version: 3.8
  setup_py_install: true
  install:
    - requirements: docs/requirements.txt
