# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements-test.txt
    - name: Lint with flake8 and black
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # check using isort and black
        make lint check=1
    - name: Test with pytest
      run: |
        pip install pytest
        pytest

  examples:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name:
        run: |
          cd examples
          python synthetic_data.py
          python flight_delays.py

      - uses: actions/upload-artifact@v2
        with:
          name: synthetic-report
          path: examples/test_data_report.html
          if-no-files-found: error

      - uses: actions/upload-artifact@v2
        with:
          name: flight-delays-report
          path: examples/flight_delays_report.html
          if-no-files-found: error
